name: Keycloak Build and Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Keycloak and Create ZIP Distribution
      run: |
        ls -l
        ./mvnw -pl quarkus/deployment,quarkus/dist -am -DskipTests clean install

  # build-docker:
  #   runs-on: ubuntu-latest

  #   needs: build

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Download Keycloak ZIP Distribution
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: keycloak-zip
  #       path: keycloak-zip

  #   - name: Build Docker Image
  #     run: |
  #       cd keycloak-zip
  #       docker build -t my-keycloak-image .
      
  #   - name: Login to Docker Hub
  #     uses: docker/login-action@v3
  #     with:
  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
  #       password: ${{ secrets.DOCKERHUB_TOKEN }}

  #   - name: Push Docker Image to Docker Hub
  #     run: |
  #       docker tag my-keycloak-image:latest $DOCKER_USERNAME/my-keycloak:latest
  #       docker push $DOCKER_USERNAME/my-keycloak:latest
